const GIG2_TABLE_NAMES = [
  "government-elections-presidential.regions-ec.1982",
  "government-elections-presidential.regions-ec.1988",
  "government-elections-presidential.regions-ec.1994",
  "government-elections-presidential.regions-ec.1999",
  "government-elections-presidential.regions-ec.2005",
  "government-elections-presidential.regions-ec.2010",
  "government-elections-presidential.regions-ec.2015",
  "government-elections-presidential.regions-ec.2019",
  "population-age_group.2012",
  "population-ethnicity.regions.2012",
  "population-gender.regions.2012",
  "population-marital_status.regions.2012",
  "population-religion.regions.2012",
  "population-total.regions.2012",
  "social-household-communication_items.regions.2012",
  "social-household-cooking_fuel.regions.2012",
  "social-household-drinking_water.2012",
  "social-household-floor_type.regions.2012",
  "social-household-lighting.regions.2012",
  "social-household-living_quarters.regions.2012",
  "social-household-relationship_to_owner.regions.2012",
  "social-household-roof_type.regions.2012",
  "social-household-rooms.2012",
  "social-household-toilet_facilities.regions.2012",
  "social-household-type_of_unit.regions.2012",
  "social-household-wall_type.regions.2012",
  "social-household-waste_disposal.regions.2012",
  "social-household-year_of_construction.regions.2012",
  "social-household_number_of_persons.regions.2012",
  "social-household_occupation_status.regions.2012",
  "social-household_ownership.regions.2012",
  "social-household_per_housing_unit.regions.2012",
  "social-household_structure.regions.2012",
];

export default GIG2_TABLE_NAMES;
